
server:
  port: 8080
  servlet:
    context-path: /

spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/market?serverTimezone=Asia/Seoul
    username: root
    password: ${PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000

    show-sql: true

logging:
  level:
    org.hibernate.type: trace